import React, { createContext, useContext, useState } from 'react'

export const LANGUAGES = {
  fr: { label: 'Français', flag: '🇫🇷' },
  en: { label: 'English',  flag: '🇬🇧' },
  es: { label: 'Español',  flag: '🇪🇸' },
  de: { label: 'Deutsch',  flag: '🇩🇪' },
  it: { label: 'Italiano', flag: '🇮🇹' },
}

const T = {
  fr: {
    // Nav
    home: 'Accueil', search: 'Recherche', favorites: 'Favoris', history: 'Historique',
    account: 'Compte', legal: 'Légal',
    // Header
    login: 'Connexion', logout: 'Déconnexion',
    // Search
    searchPlaceholder: 'Rechercher un aliment, une marque…',
    searchResults: (n) => `${n} résultat${n>1?'s':''} — Open Food Facts`,
    noResults: (q) => `Aucun résultat pour "${q}"`,
    suggestions: 'Suggestions :',
    scanBarcode: 'Scanner un code-barres',
    networkError: 'Erreur réseau. Vérifiez votre connexion internet.',
    // Product detail
    back: 'Retour',
    report: 'Signaler',
    healthProfile: 'Profil santé',
    nutritionTab: '🥗 Nutrition',
    ecoTab: '🌿 Environnement',
    originTab: '🌍 Origine',
    ingredientsTab: '🧪 Ingrédients',
    healthTab: '🧑‍⚕️ Dans 20 ans',
    ecoWorldTab: '🌱 Planète',
    nutritionPer100: 'Valeurs nutritionnelles pour 100g',
    envImpact: 'Impact environnemental',
    geographicOrigin: 'Origine géographique',
    composition: 'Composition',
    additivesDetected: 'Additifs détectés',
    allergens: 'Allergènes',
    unknownBrand: 'Marque inconnue',
    dataUnavailable: 'Donnée non disponible',
    sourceOFF: 'Source : Open Food Facts',
    // Health sim
    healthSimTitle: 'Simulation santé — 20 ans',
    bmiNow: 'IMC actuel', bmi20: 'IMC dans 20 ans', weightGain: 'Prise de poids est.',
    riskCaries: 'Caries dentaires', riskObesity: 'Surpoids / obésité',
    riskCardio: 'Maladies cardiovasculaires', riskHyper: 'Hypertension artérielle',
    riskDiabetes: 'Diabète type 2',
    riskLow: 'Risque faible', riskMod: 'Risque modéré', riskHigh: 'Risque élevé',
    simDisclaimer: '⚠️ Simulation indicative. Ne constitue pas un avis médical.',
    // Eco sim
    impactScore: 'Score impact', yearlyco2: 'CO₂ annuel estimé',
    ecoEquiv: 'Équivalences annuelles', kmCar: 'km en voiture', treeMonths: 'mois d\'absorption d\'un arbre',
    // Account
    notLoggedIn: 'Non connecté',
    loginToAccess: 'Connectez-vous pour accéder à toutes les fonctionnalités.',
    loginRegister: 'Se connecter / S\'inscrire',
    myProfile: 'Mon profil', editProfile: 'Modifier le profil',
    myFavorites: 'Mes favoris', myHistory: 'Historique',
    age: 'Âge', weight: 'Poids', height: 'Taille', activity: 'Activité',
    freq: 'Fréquence/semaine', bmi: 'IMC',
    // Auth
    signIn: 'Se connecter', signUp: 'S\'inscrire',
    email: 'Email', password: 'Mot de passe', name: 'Nom complet',
    continueWith: 'Continuer avec',
    alreadyAccount: 'Déjà un compte ? Se connecter',
    noAccount: 'Pas encore de compte ? S\'inscrire',
    twoFaTitle: 'Vérification 2FA',
    twoFaDesc: 'Un code a été envoyé à',
    codePlaceholder: 'Code 6 chiffres',
    confirm: 'Confirmer',
    // Legal
    legalTitle: 'Informations légales',
    legalDesc: 'Transparence sur les données, la vie privée et les sources.',
    // Admin
    adminTitle: 'Panel Administrateur',
    adminAccess: 'Accès restreint',
    users: 'Utilisateurs', active: 'Actifs', banned: 'Bannis', reports: 'Signalements',
    banUser: 'Bannir', restoreUser: 'Restaurer',
    // Report
    reportTitle: 'Signaler un problème',
    reportSent: 'Signalement envoyé',
    reportThanks: 'L\'équipe a été notifiée. Merci pour votre contribution !',
    send: 'Envoyer', cancel: 'Annuler', close: 'Fermer',
    // Profile modal
    profileTitle: 'Profil de simulation santé',
    save: 'Enregistrer',
    profileSaved: 'Profil mis à jour !',
    weeksPerFreq: 'fois/semaine',
    // Chemicals
    chemicalsTitle: 'Substances chimiques & risques',
    noChemicals: 'Aucun additif renseigné pour ce produit.',
    // Nutriscore
    nutriscore: 'Nutri-Score', ecoscore: 'Eco-Score',
  },
  en: {
    home: 'Home', search: 'Search', favorites: 'Favorites', history: 'History',
    account: 'Account', legal: 'Legal',
    login: 'Log in', logout: 'Log out',
    searchPlaceholder: 'Search a food product, brand…',
    searchResults: (n) => `${n} result${n>1?'s':''} — Open Food Facts`,
    noResults: (q) => `No results for "${q}"`,
    suggestions: 'Suggestions:',
    scanBarcode: 'Scan barcode',
    networkError: 'Network error. Please check your internet connection.',
    back: 'Back', report: 'Report', healthProfile: 'Health profile',
    nutritionTab: '🥗 Nutrition', ecoTab: '🌿 Environment', originTab: '🌍 Origin',
    ingredientsTab: '🧪 Ingredients', healthTab: '🧑‍⚕️ In 20 years', ecoWorldTab: '🌱 Planet',
    nutritionPer100: 'Nutrition facts per 100g',
    envImpact: 'Environmental impact', geographicOrigin: 'Geographic origin',
    composition: 'Composition', additivesDetected: 'Additives detected',
    allergens: 'Allergens', unknownBrand: 'Unknown brand',
    dataUnavailable: 'Data not available', sourceOFF: 'Source: Open Food Facts',
    healthSimTitle: 'Health simulation — 20 years',
    bmiNow: 'Current BMI', bmi20: 'BMI in 20 years', weightGain: 'Est. weight gain',
    riskCaries: 'Tooth decay', riskObesity: 'Overweight / obesity',
    riskCardio: 'Cardiovascular disease', riskHyper: 'Hypertension', riskDiabetes: 'Type 2 diabetes',
    riskLow: 'Low risk', riskMod: 'Moderate risk', riskHigh: 'High risk',
    simDisclaimer: '⚠️ Indicative simulation. Not medical advice.',
    impactScore: 'Impact score', yearlyco2: 'Yearly CO₂ estimate',
    ecoEquiv: 'Annual equivalents', kmCar: 'km by car', treeMonths: 'months of tree absorption',
    notLoggedIn: 'Not logged in',
    loginToAccess: 'Log in to access all features.',
    loginRegister: 'Log in / Sign up',
    myProfile: 'My profile', editProfile: 'Edit profile',
    myFavorites: 'My favorites', myHistory: 'History',
    age: 'Age', weight: 'Weight', height: 'Height', activity: 'Activity',
    freq: 'Frequency/week', bmi: 'BMI',
    signIn: 'Log in', signUp: 'Sign up',
    email: 'Email', password: 'Password', name: 'Full name',
    continueWith: 'Continue with',
    alreadyAccount: 'Already have an account? Log in',
    noAccount: 'No account yet? Sign up',
    twoFaTitle: '2FA Verification', twoFaDesc: 'A code was sent to',
    codePlaceholder: '6-digit code', confirm: 'Confirm',
    legalTitle: 'Legal information', legalDesc: 'Transparency about data, privacy and sources.',
    adminTitle: 'Admin Panel', adminAccess: 'Restricted access',
    users: 'Users', active: 'Active', banned: 'Banned', reports: 'Reports',
    banUser: 'Ban', restoreUser: 'Restore',
    reportTitle: 'Report a problem', reportSent: 'Report submitted',
    reportThanks: 'The team has been notified. Thank you!',
    send: 'Send', cancel: 'Cancel', close: 'Close',
    profileTitle: 'Health simulation profile', save: 'Save',
    profileSaved: 'Profile updated!', weeksPerFreq: 'times/week',
    chemicalsTitle: 'Chemical substances & risks', noChemicals: 'No additives listed for this product.',
    nutriscore: 'Nutri-Score', ecoscore: 'Eco-Score',
  },
  es: {
    home: 'Inicio', search: 'Buscar', favorites: 'Favoritos', history: 'Historial',
    account: 'Cuenta', legal: 'Legal',
    login: 'Iniciar sesión', logout: 'Cerrar sesión',
    searchPlaceholder: 'Buscar un alimento, marca…',
    searchResults: (n) => `${n} resultado${n>1?'s':''} — Open Food Facts`,
    noResults: (q) => `Sin resultados para "${q}"`,
    suggestions: 'Sugerencias:', scanBarcode: 'Escanear código de barras',
    networkError: 'Error de red. Verifique su conexión.',
    back: 'Volver', report: 'Reportar', healthProfile: 'Perfil de salud',
    nutritionTab: '🥗 Nutrición', ecoTab: '🌿 Medioambiente', originTab: '🌍 Origen',
    ingredientsTab: '🧪 Ingredientes', healthTab: '🧑‍⚕️ En 20 años', ecoWorldTab: '🌱 Planeta',
    nutritionPer100: 'Valores nutricionales por 100g',
    envImpact: 'Impacto medioambiental', geographicOrigin: 'Origen geográfico',
    composition: 'Composición', additivesDetected: 'Aditivos detectados',
    allergens: 'Alérgenos', unknownBrand: 'Marca desconocida',
    dataUnavailable: 'Dato no disponible', sourceOFF: 'Fuente: Open Food Facts',
    healthSimTitle: 'Simulación de salud — 20 años',
    bmiNow: 'IMC actual', bmi20: 'IMC en 20 años', weightGain: 'Aumento de peso est.',
    riskCaries: 'Caries dentales', riskObesity: 'Sobrepeso / obesidad',
    riskCardio: 'Enfermedades cardiovasculares', riskHyper: 'Hipertensión', riskDiabetes: 'Diabetes tipo 2',
    riskLow: 'Riesgo bajo', riskMod: 'Riesgo moderado', riskHigh: 'Riesgo alto',
    simDisclaimer: '⚠️ Simulación indicativa. No es consejo médico.',
    impactScore: 'Puntuación impacto', yearlyco2: 'CO₂ anual estimado',
    ecoEquiv: 'Equivalencias anuales', kmCar: 'km en coche', treeMonths: 'meses de absorción árbol',
    notLoggedIn: 'No conectado', loginToAccess: 'Inicia sesión para acceder a todas las funciones.',
    loginRegister: 'Iniciar sesión / Registrarse',
    myProfile: 'Mi perfil', editProfile: 'Editar perfil',
    myFavorites: 'Mis favoritos', myHistory: 'Historial',
    age: 'Edad', weight: 'Peso', height: 'Altura', activity: 'Actividad',
    freq: 'Frecuencia/semana', bmi: 'IMC',
    signIn: 'Iniciar sesión', signUp: 'Registrarse',
    email: 'Correo', password: 'Contraseña', name: 'Nombre completo',
    continueWith: 'Continuar con',
    alreadyAccount: '¿Ya tienes cuenta? Iniciar sesión',
    noAccount: '¿Sin cuenta? Registrarse',
    twoFaTitle: 'Verificación 2FA', twoFaDesc: 'Se envió un código a',
    codePlaceholder: 'Código 6 dígitos', confirm: 'Confirmar',
    legalTitle: 'Información legal', legalDesc: 'Transparencia sobre datos, privacidad y fuentes.',
    adminTitle: 'Panel de administración', adminAccess: 'Acceso restringido',
    users: 'Usuarios', active: 'Activos', banned: 'Bloqueados', reports: 'Reportes',
    banUser: 'Bloquear', restoreUser: 'Restaurar',
    reportTitle: 'Reportar un problema', reportSent: 'Reporte enviado',
    reportThanks: '¡El equipo ha sido notificado. Gracias!',
    send: 'Enviar', cancel: 'Cancelar', close: 'Cerrar',
    profileTitle: 'Perfil de simulación de salud', save: 'Guardar',
    profileSaved: '¡Perfil actualizado!', weeksPerFreq: 'veces/semana',
    chemicalsTitle: 'Sustancias químicas y riesgos', noChemicals: 'Sin aditivos listados.',
    nutriscore: 'Nutri-Score', ecoscore: 'Eco-Score',
  },
  de: {
    home: 'Start', search: 'Suche', favorites: 'Favoriten', history: 'Verlauf',
    account: 'Konto', legal: 'Rechtliches',
    login: 'Anmelden', logout: 'Abmelden',
    searchPlaceholder: 'Lebensmittel, Marke suchen…',
    searchResults: (n) => `${n} Ergebnis${n>1?'se':''} — Open Food Facts`,
    noResults: (q) => `Keine Ergebnisse für "${q}"`,
    suggestions: 'Vorschläge:', scanBarcode: 'Barcode scannen',
    networkError: 'Netzwerkfehler. Bitte Internetverbindung prüfen.',
    back: 'Zurück', report: 'Melden', healthProfile: 'Gesundheitsprofil',
    nutritionTab: '🥗 Ernährung', ecoTab: '🌿 Umwelt', originTab: '🌍 Herkunft',
    ingredientsTab: '🧪 Zutaten', healthTab: '🧑‍⚕️ In 20 Jahren', ecoWorldTab: '🌱 Erde',
    nutritionPer100: 'Nährwerte pro 100g',
    envImpact: 'Umweltauswirkung', geographicOrigin: 'Geografischer Ursprung',
    composition: 'Zusammensetzung', additivesDetected: 'Erkannte Zusatzstoffe',
    allergens: 'Allergene', unknownBrand: 'Unbekannte Marke',
    dataUnavailable: 'Daten nicht verfügbar', sourceOFF: 'Quelle: Open Food Facts',
    healthSimTitle: 'Gesundheitssimulation — 20 Jahre',
    bmiNow: 'Aktueller BMI', bmi20: 'BMI in 20 Jahren', weightGain: 'Gesch. Gewichtszunahme',
    riskCaries: 'Karies', riskObesity: 'Übergewicht / Fettleibigkeit',
    riskCardio: 'Herzkreislauferkrankungen', riskHyper: 'Bluthochdruck', riskDiabetes: 'Typ-2-Diabetes',
    riskLow: 'Geringes Risiko', riskMod: 'Moderates Risiko', riskHigh: 'Hohes Risiko',
    simDisclaimer: '⚠️ Indikative Simulation. Kein medizinischer Rat.',
    impactScore: 'Impact-Score', yearlyco2: 'Jährlicher CO₂-Schätzwert',
    ecoEquiv: 'Jährliche Äquivalente', kmCar: 'km mit dem Auto', treeMonths: 'Monate Baumabsorption',
    notLoggedIn: 'Nicht angemeldet', loginToAccess: 'Melden Sie sich an, um alle Funktionen zu nutzen.',
    loginRegister: 'Anmelden / Registrieren',
    myProfile: 'Mein Profil', editProfile: 'Profil bearbeiten',
    myFavorites: 'Meine Favoriten', myHistory: 'Verlauf',
    age: 'Alter', weight: 'Gewicht', height: 'Größe', activity: 'Aktivität',
    freq: 'Häufigkeit/Woche', bmi: 'BMI',
    signIn: 'Anmelden', signUp: 'Registrieren',
    email: 'E-Mail', password: 'Passwort', name: 'Vollständiger Name',
    continueWith: 'Weiter mit',
    alreadyAccount: 'Bereits ein Konto? Anmelden',
    noAccount: 'Noch kein Konto? Registrieren',
    twoFaTitle: '2FA-Verifizierung', twoFaDesc: 'Ein Code wurde gesendet an',
    codePlaceholder: '6-stelliger Code', confirm: 'Bestätigen',
    legalTitle: 'Rechtliche Informationen', legalDesc: 'Transparenz über Daten, Datenschutz und Quellen.',
    adminTitle: 'Admin-Panel', adminAccess: 'Eingeschränkter Zugang',
    users: 'Benutzer', active: 'Aktiv', banned: 'Gesperrt', reports: 'Meldungen',
    banUser: 'Sperren', restoreUser: 'Wiederherstellen',
    reportTitle: 'Problem melden', reportSent: 'Meldung gesendet',
    reportThanks: 'Das Team wurde benachrichtigt. Danke!',
    send: 'Senden', cancel: 'Abbrechen', close: 'Schließen',
    profileTitle: 'Gesundheitssimulationsprofil', save: 'Speichern',
    profileSaved: 'Profil aktualisiert!', weeksPerFreq: 'x/Woche',
    chemicalsTitle: 'Chemische Stoffe & Risiken', noChemicals: 'Keine Zusatzstoffe aufgeführt.',
    nutriscore: 'Nutri-Score', ecoscore: 'Eco-Score',
  },
  it: {
    home: 'Home', search: 'Cerca', favorites: 'Preferiti', history: 'Cronologia',
    account: 'Account', legal: 'Legale',
    login: 'Accedi', logout: 'Esci',
    searchPlaceholder: 'Cerca un alimento, marca…',
    searchResults: (n) => `${n} risultat${n>1?'i':'o'} — Open Food Facts`,
    noResults: (q) => `Nessun risultato per "${q}"`,
    suggestions: 'Suggerimenti:', scanBarcode: 'Scansiona codice a barre',
    networkError: 'Errore di rete. Controlla la connessione.',
    back: 'Indietro', report: 'Segnala', healthProfile: 'Profilo salute',
    nutritionTab: '🥗 Nutrizione', ecoTab: '🌿 Ambiente', originTab: '🌍 Origine',
    ingredientsTab: '🧪 Ingredienti', healthTab: '🧑‍⚕️ Tra 20 anni', ecoWorldTab: '🌱 Pianeta',
    nutritionPer100: 'Valori nutrizionali per 100g',
    envImpact: 'Impatto ambientale', geographicOrigin: 'Origine geografica',
    composition: 'Composizione', additivesDetected: 'Additivi rilevati',
    allergens: 'Allergeni', unknownBrand: 'Marca sconosciuta',
    dataUnavailable: 'Dato non disponibile', sourceOFF: 'Fonte: Open Food Facts',
    healthSimTitle: 'Simulazione salute — 20 anni',
    bmiNow: 'IMC attuale', bmi20: 'IMC tra 20 anni', weightGain: 'Aumento peso stimato',
    riskCaries: 'Carie dentali', riskObesity: 'Sovrappeso / obesità',
    riskCardio: 'Malattie cardiovascolari', riskHyper: 'Ipertensione', riskDiabetes: 'Diabete tipo 2',
    riskLow: 'Rischio basso', riskMod: 'Rischio moderato', riskHigh: 'Rischio alto',
    simDisclaimer: '⚠️ Simulazione indicativa. Non è un consiglio medico.',
    impactScore: 'Punteggio impatto', yearlyco2: 'CO₂ annuale stimata',
    ecoEquiv: 'Equivalenti annuali', kmCar: 'km in auto', treeMonths: 'mesi di assorbimento albero',
    notLoggedIn: 'Non connesso', loginToAccess: 'Accedi per tutte le funzionalità.',
    loginRegister: 'Accedi / Registrati',
    myProfile: 'Il mio profilo', editProfile: 'Modifica profilo',
    myFavorites: 'I miei preferiti', myHistory: 'Cronologia',
    age: 'Età', weight: 'Peso', height: 'Altezza', activity: 'Attività',
    freq: 'Frequenza/settimana', bmi: 'IMC',
    signIn: 'Accedi', signUp: 'Registrati',
    email: 'Email', password: 'Password', name: 'Nome completo',
    continueWith: 'Continua con',
    alreadyAccount: 'Hai già un account? Accedi',
    noAccount: 'Nessun account? Registrati',
    twoFaTitle: 'Verifica 2FA', twoFaDesc: 'Un codice è stato inviato a',
    codePlaceholder: 'Codice 6 cifre', confirm: 'Conferma',
    legalTitle: 'Informazioni legali', legalDesc: 'Trasparenza su dati, privacy e fonti.',
    adminTitle: 'Pannello amministratore', adminAccess: 'Accesso limitato',
    users: 'Utenti', active: 'Attivi', banned: 'Sospesi', reports: 'Segnalazioni',
    banUser: 'Sospendi', restoreUser: 'Ripristina',
    reportTitle: 'Segnala un problema', reportSent: 'Segnalazione inviata',
    reportThanks: 'Il team è stato notificato. Grazie!',
    send: 'Invia', cancel: 'Annulla', close: 'Chiudi',
    profileTitle: 'Profilo simulazione salute', save: 'Salva',
    profileSaved: 'Profilo aggiornato!', weeksPerFreq: 'volte/settimana',
    chemicalsTitle: 'Sostanze chimiche & rischi', noChemicals: 'Nessun additivo elencato.',
    nutriscore: 'Nutri-Score', ecoscore: 'Eco-Score',
  },
}

const LangContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('fi_lang') || 'fr' } catch { return 'fr' }
  })
  const t = (key, ...args) => {
    const val = T[lang]?.[key] ?? T['fr']?.[key] ?? key
    return typeof val === 'function' ? val(...args) : val
  }
  const changeLang = (l) => { setLang(l); try { localStorage.setItem('fi_lang', l) } catch {} }
  return (
    <LangContext.Provider value={{ lang, changeLang, t, languages: LANGUAGES }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLang must be used within LanguageProvider')
  return ctx
}
